apiVersion: v1
kind: Pod
metadata:
  name: ready
spec:
  containers:
  - name: helloworld
    image: itsmetommy/helloworld:latest
    ports:
    - containerPort: 80
    readinessProbe:
      initialDelaySeconds: 10
      httpGet:
        path: /
        port: 80