apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: itsmetommy/helloworld:2.0.0
        ports:
        - containerPort: 80