apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: d2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: itsmetommy/helloworld:2.0.0
        name: helloworld