apiVersion: v1
kind: Pod
metadata:
  name: label2
  labels:
    env: production
    owner: tommy
spec:
  containers:
  - name: helloworld
    image: itsmetommy/helloworld:latest
    ports:
    - containerPort: 80