apiVersion: v1
kind: ReplicationController
metadata:
  name: rc2
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      name: my-app
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: itsmetommy/helloworld:latest
        ports:
        - containerPort: 80