apiVersion: v1
kind: Pod
metadata:
  name: envs
spec:
  containers:
  - name: helloworld
    image: itsmetommy/helloworld:latest
    ports:
    - containerPort: 80
    env:
    - name: SERVICE_VERSION
      value: "2.0.0"